
{{- if (and .Values.apisix.enabled .Values.apisix.podDisruptionBudget.enabled) }}
{{ if semverCompare "<1.21-0" .Capabilities.KubeVersion.Version -}}
apiVersion: policy/v1beta1
{{- else -}}
apiVersion: policy/v1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "apisix.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apisix.labels" . | nindent 4 }}
spec:
{{- if .Values.apisix.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.apisix.podDisruptionBudget.minAvailable }}
{{- else }}
  maxUnavailable: {{ .Values.apisix.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
{{- include "apisix.selectorLabels" . | nindent 6 }}
{{- end }}
