{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.serviceMonitor.name | default (include "apisix.fullname" .) }}
  namespace: {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "apisix.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.labels }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.serviceMonitor.annotations }}
  annotations: {{- toYaml .Values.serviceMonitor.annotations | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "apisix.labels" . | nindent 6 }}
      app.kubernetes.io/service: apisix-gateway
  endpoints:
  - scheme: http
    targetPort: prometheus
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
