apiVersion: v1
data:
  config.yaml: |
    # log options
    log_level: {{ .Values.config.logLevel | quote }}
    log_output: {{ .Values.config.logOutput | quote }}
    http_listen: {{ .Values.config.httpListen | quote }}
    enable_profiling: {{ .Values.config.enableProfiling }}
    kubernetes:
      kubeconfig: {{ .Values.config.kubernetes.kubeconfig | quote }}
      resync_interval: {{ .Values.config.kubernetes.resyncInterval | quote }}
      {{- if gt (len .Values.config.kubernetes.appNamespaces) 0 }}
      app_namespaces:
      {{- range .Values.config.kubernetes.appNamespaces }}
      - {{ . | quote }}
      {{- end }}
      {{- end }}
      ingress_class: {{ .Values.config.kubernetes.ingressClass | quote }}
      ingress_version: {{ .Values.config.kubernetes.ingressVersion | quote }}
      apisix_route_version: {{ .Values.config.kubernetes.apisixRouteVersion | quote }}
    apisix:
      base_url: {{ .Values.config.apisix.baseURL | quote }}
      admin_key: {{ .Values.config.apisix.adminKey | quote }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "apisix-ingress-controller.labels" . | nindent 4 }}
