apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apisix-ingress-controller.fullname" . }}
  labels:
    {{- include "apisix-ingress-controller.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "apisix-ingress-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "apisix-ingress-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "apisix-ingress-controller.serviceAccountName" . }}
      volumes:
        - name: configuration
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: config.yaml
                path: config.yaml
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /ingress-apisix/apisix-ingress-controller
            - ingress
            - --config-path
            - /ingress-apisix/conf/config.yaml
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ (.Values.config.httpListen | split ":")._1 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ (.Values.config.httpListen | split ":")._1 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ (.Values.config.httpListen | split ":")._1 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /ingress-apisix/conf
              name: configuration
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
