{{- if not .Values.portal.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "developer-portal-fe.fullname" . }}-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "developer-portal-fe.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.portal.token }}
  portal-token: {{ .Values.portal.token | b64enc | quote }}
  {{- else }}
  portal-token: ""
  {{- end }}
  {{- if .Values.auth.secret }}
  auth-secret: {{ .Values.auth.secret | b64enc | quote }}
  {{- else }}
  auth-secret: ""
  {{- end }}
  {{- if .Values.db.url }}
  db-url: {{ .Values.db.url | b64enc | quote }}
  {{- else }}
  db-url: ""
  {{- end }}
{{- end }}
