apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devportal.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  devportal.yaml: |-
    server:
      listen:
        host: 0.0.0.0
        port: {{ .Values.server.http.port }}
        enable: {{ .Values.server.http.enabled }}
      ssl:
        enable: {{ .Values.server.tls.enabled }}
        host: "0.0.0.0"
        port: {{ .Values.server.tls.port }}
        cert: "/usr/local/apisix-dashboard/tls/tls.crt"
        key: "/usr/local/apisix-dashboard/tls/tls.key"
        {{- if .Values.server.tls.client_cert_auth }}
        client_cert_auth: true
        trusted_ca: "/usr/local/apisix-dashboard/tls/ca.crt"
        {{- end }}

    etcd:
      name: {{ .Values.etcd.name }}
      {{- if .Values.etcd.builtin }}
      endpoints:
        - "http://{{ .Release.Name }}-etcd.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.etcd.service.ports.client }}"
      {{- else }}
      endpoints:
        {{- range $value := .Values.etcd.hosts }}
        - "{{ $value }}"
        {{- end }}
      {{- end }}
      auth_enabled: {{ .Values.etcd.auth.rbac.enabled }}
      username: {{ .Values.etcd.auth.rbac.user | quote }}
      password: {{ .Values.etcd.auth.rbac.password | quote }}
      prefix: {{ .Values.etcd.prefix -}}
      {{- if .Values.etcd.auth.tls.enabled }}
      mtls:
        enable: {{ .Values.etcd.auth.tls.enabled }}
        key_file: "/usr/local/apisix-dashboard/self-etcd-ssl/{{ .Values.etcd.auth.tls.certKeyFilename }}"
        cert_file: "/usr/local/apisix-dashboard/self-etcd-ssl/{{ .Values.etcd.auth.tls.certFilename }}"
        ca_file: "/usr/local/apisix-dashboard/self-etcd-ssl/{{ .Values.etcd.auth.tls.certCAFilename }}"
      {{- end }}
    log:
      error_log:
        level: {{ .Values.log.error_log.level }}
        file_path:
          {{ .Values.log.error_log.file_path }}
      access_log:
        file_path:
          {{ .Values.log.access_log.file_path }}

    auth:
      secret: {{ .Values.auth.secret }}
      session:
        age: {{.Values.auth.session.age }}
        prefix: {{.Values.auth.session.prefix | quote }}
      users:
      {{ range .Values.auth.users }}
        - username: {{ .username }}
          password: {{ .password }}
      {{ end }}

    docs:
      api_docs:
        enable: {{ .Values.docs.api_docs.enable }}
        path: {{ .Values.docs.api_docs.path }}

    cors:
      enabled: {{ .Values.cors.enabled }}
      access_control_allow_origin: {{ .Values.cors.access_control_allow_origin | quote }}
      access_control_allow_credentials: {{ .Values.cors.access_control_allow_credentials | quote }}
      access_control_allow_headers: {{ .Values.cors.access_control_allow_headers | quote }}
      access_control_allow_methods: {{ .Values.cors.access_control_allow_methods | quote }}

    session_options_config:
      same_site: {{ .Values.session_options_config.same_site }}
      secure: {{ .Values.session_options_config.secure }}
