apiVersion: v1
data:
  config.yaml: |-
    # log options
    log_level: {{ .Values.config.logLevel | quote }}
    log_output: {{ .Values.config.logOutput | quote }}
    cert_file: {{ .Values.config.certFile | quote }}
    key_file: {{ .Values.config.keyFile | quote }}
    http_listen: {{ .Values.config.httpListen | quote }}
    https_listen: {{ .Values.config.httpsListen | quote }}
    ingress_publish_service: {{ .Values.config.ingressPublishService | quote }}
    {{- if gt (len .Values.config.ingressStatusAddress) 0 }}
    ingress_status_address:
    {{- range .Values.config.ingressStatusAddress }}
    - {{ . | quote }}
    {{- end }}
    {{- end }}
    enable_profiling: {{ .Values.config.enableProfiling }}
    apisix_resource_sync_interval: {{ .Values.config.apisixResourceSyncInterval }}
    plugin_metadata_cm: {{ .Values.config.pluginMetadataCM | quote }}
    kubernetes:
      kubeconfig: {{ .Values.config.kubernetes.kubeconfig | quote }}
      resync_interval: {{ .Values.config.kubernetes.resyncInterval | quote }}

      {{- if gt (len .Values.config.kubernetes.namespaceSelector) 0 }}
      namespace_selector:
      {{- range .Values.config.kubernetes.namespaceSelector }}
      - {{ . | quote }}
      {{- end }}
      {{- end }}
      election_id: {{ .Values.config.kubernetes.electionId | quote }}
      ingress_class: {{ .Values.config.kubernetes.ingressClass | quote }}
      ingress_version: {{ .Values.config.kubernetes.ingressVersion | quote }}
      watch_endpointslices: {{ .Values.config.kubernetes.watchEndpointSlices }}
      apisix_route_version: {{ .Values.config.kubernetes.apisixRouteVersion | quote }}
      enable_gateway_api: {{ .Values.config.kubernetes.enableGatewayAPI }}
      apisix_version: {{ .Values.config.kubernetes.apiVersion | quote }}
    dashboard:
      admin_api_version: {{ .Values.config.dashboard.adminAPIVersion | quote }}
      {{- if .Values.config.dashboard.baseURL }}
      default_cluster_base_url: {{ .Values.config.dashboard.baseURL }}/apisix/admin
      {{- end }}
      {{- if .Values.config.dashboard.existingSecret }}
      default_cluster_admin_key: "{{"{{"}}.DEFAULT_CLUSTER_ADMIN_KEY{{"}}"}}"
      {{- else }}
      default_cluster_admin_key: {{ .Values.config.dashboard.adminKey | quote }}
      {{- end }}
      default_cluster_name: {{ .Values.config.dashboard.clusterName | quote }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apisix-ingress-controller.labels" . | nindent 4 }}
