apiVersion: v2
name: aisix-cp
description: Helm chart for AISIX control plane (cp-api, dp-manager, dashboard)
type: application
version: 0.4.0
appVersion: "0.4.0"

maintainers:
  - name: API7
    email: support@api7.ai
    url: https://api7.ai

dependencies:
  - name: postgresql
    condition: postgresql.builtin
    version: "12.12.10"
    repository: "https://charts.bitnami.com/bitnami"
