apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api7-ingress-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    {{- include "api7-ingress-controller.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api7-ingress-controller.selectorLabels" . | nindent 6 }}
  {{- with .Values.updateStrategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- range $key, $value := $.Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "api7-ingress-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "api7-ingress-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: configuration
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: config.yaml
                path: config.yaml
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /ingress-apisix/api7-ingress-controller
            - ingress
            - --config-path
            - /ingress-apisix/conf/config.yaml
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ (.Values.config.httpListen | split ":")._1 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ (.Values.config.httpListen | split ":")._1 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ (.Values.config.httpListen | split ":")._1 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /ingress-apisix/conf/config.yaml
              name: configuration
              subPath: config.yaml
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {{- if .Values.config.dashboard.existingSecret }}
          - name: DEFAULT_CLUSTER_ADMIN_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.config.dashboard.existingSecret | quote }}
                key: {{ include "api7-ingress-controller.credentials.secretAdminKey" . }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (. | toYaml) $ | nindent 8 }}
      {{- end }}
