apiVersion: v1
kind: Service
metadata:
  name: {{ include "api7-ingress-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api7-ingress-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ (.Values.config.httpListen | split ":")._1 }}
      protocol: TCP
      name: http
  selector:
    {{- include "api7-ingress-controller.selectorLabels" . | nindent 4 }}
