{{- if and (not .Values.postgresql.builtin) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aisix-cp.fullname" . }}-external-db
  labels:
    {{- include "aisix-cp.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ required "externalDatabase.password is required when existingSecret is not set" .Values.externalDatabase.password | b64enc }}
{{- end }}
