{{- if (.Values.api_usage | default dict).enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api7ee3.fullname" . }}-api-usage
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "api7ee3.labels" . | nindent 4 }}
  {{- with .Values.api_usage.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api_usage.service.type }}
  ports:
    - port: {{ .Values.api_usage.service.port }}
      targetPort: http
      protocol: TCP
      name: http

  selector:
    {{- include "api7ee3.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-usage
{{- end }}
