kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "api7ee3.fullname" . }}-developer-portal-config
  namespace: {{ .Release.Namespace | quote }}
data:
  config.yaml: |
  {{- toYaml .Values.developer_portal_configuration | nindent 4 }}
