apiVersion: v1
kind: Service
metadata:
  name: {{ include "api7ee3.fullname" . }}-dp-manager
  labels:
    {{- include "api7ee3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dp_manager_service.type }}
  ports:
    - port: {{ .Values.dp_manager_service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.dp_manager_configuration.server.status_listen.port }}
      targetPort: status
      protocol: TCP
      name: status

  selector:
    {{- include "api7ee3.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dp-manager
