apiVersion: v1
kind: Service
metadata:
  name: {{ include "aisix-cloud.fullname" . }}-ui
  labels:
    {{- include "aisix-cloud.labels" . | nindent 4 }}
    {{- include "aisix-cloud.selectorLabels" (dict "root" . "component" "ui") | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aisix-cloud.selectorLabels" (dict "root" . "component" "ui") | nindent 4 }}
