{{- if and .Values.admin.enabled (not .Values.deployment.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aisix.fullname" . }}-admin-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aisix.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-key: {{ (index .Values.deployment.admin.adminKey 0).key | quote }}
{{- end }}
