{{- include "aisix.validateValues" . }}
{{- if not .Values.controlPlane.certificate.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aisix.certSecretName" . }}
  labels:
    {{- include "aisix.labels" . | nindent 4 }}
    {{- include "aisix.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.controlPlane.certificate.certKey }}: |-
{{ .Values.controlPlane.certificate.cert | trim | indent 4 }}
  {{ .Values.controlPlane.certificate.keyKey }}: |-
{{ .Values.controlPlane.certificate.key | trim | indent 4 }}
  {{ .Values.controlPlane.certificate.caKey }}: |-
{{ .Values.controlPlane.certificate.ca | trim | indent 4 }}
{{- end }}
{{- if and (eq .Values.rateLimit.backend "redis") (not .Values.rateLimit.redis.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aisix.redisSecretName" . }}
  labels:
    {{- include "aisix.labels" . | nindent 4 }}
    {{- include "aisix.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  redis-url: {{ .Values.rateLimit.redis.url | quote }}
{{- end }}
