apiVersion: v1
kind: Service
metadata:
  name: {{ include "aisix.fullname" . }}
  labels:
    {{- include "aisix.labels" . | nindent 4 }}
    {{- include "aisix.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    - name: proxy
      port: {{ .Values.service.port }}
      targetPort: proxy
      protocol: TCP
      {{- if and .Values.service.nodePort (ne (toString .Values.service.type) "ClusterIP") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "aisix.selectorLabels" . | nindent 4 }}
