apiVersion: v1
kind: Service
metadata:
  name: {{ include "aisix.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aisix.labels" . | nindent 4 }}
    app.kubernetes.io/service: aisix-admin
  {{- with .Values.adminService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.adminService.type }}
  ports:
    - name: admin
      port: {{ .Values.adminService.port }}
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "aisix.selectorLabels" . | nindent 4 }}
