name: Run E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install Dependencies
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.2.0
          go install sigs.k8s.io/kind@v0.11.0
          sudo cp ~/go/bin/ginkgo /usr/local/bin
          sudo cp ~/go/bin/kind /usr/local/bin
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo cp ./kustomize /usr/local/bin
          # pull docker images
          docker pull api7ee.azurecr.io/api7-dashboard:2.13.2302
          docker pull api7ee.azurecr.io/api7-gateway:2.13.2302
      - name: Run E2E Test Suites
        working-directory: ./
        run: |
          make e2e-test
